- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/Dispatcher.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/EventDispatcherConfiguration.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/EventDispatchingHandler.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/HandlerPool.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/JobLauncher.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/ServiceInvoker.java
> Handle function un-registration in event dispatcher

- .gitignore
- README.adoc
- dockerize
- node-function-web-handler/.dockerignore
- node-function-web-handler/Dockerfile
- node-function-web-handler/package-lock.json
- node-function-web-handler/package.json
- node-function-web-handler/server.js
- samples/greeter-function.yaml
- samples/greetings-topic.yaml
- samples/node-handler.yaml
- samples/node/hello.js
- samples/numbers-topic.yaml
- samples/square-function.yaml
- teardown
Builds on top of my other PR
Fixes #20
> Adds node handler and example

- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/EventDispatcherConfiguration.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/EventDispatchingHandler.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/JobLauncher.java
- faas
add owner reference to job metadata
> delete job when owning function is deleted

- event-dispatcher/pom.xml
- function-invokers/java-function-invoker/pom.xml
- function-invokers/node-function-invoker/pom.xml
- function-invokers/python2-function-invoker/pom.xml
- function-invokers/shell-function-invoker/pom.xml
- function-sidecar/pom.xml
- pom.xml
- topic-controller/pom.xml
- topic-gateway/pom.xml
- zipkin-server/pom.xml
to ensure that images can be identified as associated with sk8s regardless of their org.
> Add docker image prefix to all artifacts

- charts/sk8s/templates/event-dispatcher-deployment.yaml
- charts/sk8s/templates/topic-controller-deployment.yaml
- charts/sk8s/templates/topic-gateway-deployment.yaml
> Adding liveness/readiness probes

- event-dispatcher/pom.xml
- function-invokers/java-function-invoker/pom.xml
- function-invokers/node-function-invoker/pom.xml
- function-invokers/python2-function-invoker/pom.xml
- function-invokers/shell-function-invoker/pom.xml
- function-sidecar/pom.xml
- pom.xml
- topic-controller/pom.xml
- topic-gateway/pom.xml
- zipkin-server/pom.xml
- Removing docker.org property
> Reverting image prefix change

- charts/sk8s/templates/event-dispatcher-service.yaml
- charts/sk8s/templates/grafana-deployment.yaml
- charts/sk8s/templates/grafana-service.yaml
- charts/sk8s/templates/prometheus-configmap.yaml
- charts/sk8s/templates/prometheus-deployment.yaml
- charts/sk8s/templates/prometheus-service.yaml
- charts/sk8s/templates/zipkin-deployment.yaml
- charts/sk8s/values.yaml
- adding `enable.metricsDashboard` flag that defaults to false
- adding `enable.tracingDashboard` flag that defaults to false
- setting all sk8s image tags to 0.0.1-SNAPSHOT
- defining tags for zookeeper and kafka images
Resolves #75
Resolves #74
> Adding Grafana/Prometheus to Helm chart

- charts/sk8s/Chart.yaml
- charts/sk8s/values.yaml
- setting services to use LoadBalancer
- setting version to 0.0.1 to match project
> Updating chart

- samples/java/greeter/README.adoc
- samples/node/square/README.adoc
- samples/python/sentiments/README.adoc
- samples/python/uppercase/README.adoc
- samples/shell/echo/README.adoc
- samples/shell/wordcount/README.adoc
- we can no longer tail the logs before the message is published since we scale to 0
> Move log tailing after publish

- charts/sk8s/templates/kafka-deployment.yaml
- charts/sk8s/templates/kafka-service.yaml
- charts/sk8s/values.yaml
- config/event-dispatcher-deployment.yaml
- config/event-dispatcher-service.yaml
- config/topic-controller-deployment.yaml
- config/topic-controller-service.yaml
- config/topic-gateway-deployment.yaml
- config/topic-gateway-service-nodeport.yaml
- publish
- teardown
- makes it easier to write scripts that work against both manual and helm installed system
> Make the resource labeling more consistent

- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/EventDispatcherConfiguration.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/FunctionDeployer.java
- event-dispatcher/src/main/java/io/sk8s/event/dispatcher/SidecarProperties.java
env var to pass would be: `SK8S_FUNCTION_CONTROLLER_SIDECAR_TAG`
> expose sidecar image tag property

- charts/sk8s/values.yaml
addresses https://ci.faas.to.cf-app.com/teams/pfs/pipelines/sk8s/jobs/deploy-sk8s/builds/48
Signed-off-by: Jamie Klassen <cklassen@pivotal.io>
> change entry in values.yaml

- function-invokers/java-function-invoker/src/main/java/io/sk8s/invoker/java/server/FunctionConfiguration.java
Otherwise it can't load any more classes at runtime, which is
obviously a bad thing.
> Don't close the class loader that is going to be used in functions

- function-controller/src/main/java/io/sk8s/function/controller/LagTracker.java
> reassign partitions when out of sync

- function-invokers/java-function-invoker/pom.xml
Improves startup time by approx. 25%.  See gh-84.
> Remove prometheus starter

- publish
- request
> Modified publish/request to work with service using LoadBalancer

- function-invokers/java-function-invoker/src/main/java/io/sk8s/invoker/java/server/FunctionConfiguration.java
- function-invokers/java-function-invoker/src/test/java/io/sk8s/invoker/java/function/Frenchizer.java
This is quite useful if you want to add a @PostConstruct for
instance (could be used to initialize Spring in a mini-context
if not already there)
> Use Spring to call bean lifecycle methods on created functions

- config/function-controller-deployment.yaml
to be merged after https://github.com/projectriff/function-controller/pull/2
> change sidecar property

- README.adoc
- build-function-controller
- build-function-sidecar
- build-helper
- build-http-gateway
- build-java-function-invoker
- build-model
- build-node-function-invoker
- build-python2-function-invoker
- build-shell-function-invoker
- build-topic-controller
> Use 'upstream' as the remote alias for repos.

- config/rbac/riff-cluster-rolebinding.yaml
- config/rbac/riff-clusterrole.yaml
- config/rbac/riff-role.yaml
- add ClusterRole allowing access to CustomResourceDefinitions
- add ClusterRoleBinding for new ClusterRole
> Fix the RBAC config scripts

- samples/python/uppercase/py/func.py
Resolves #208 
Depends on corresponding PRs in function-proto and function-sidecar
> Enable GRPC Streaming in Python uppercase sample

- Getting-Started.adoc
- adding some requirements and version info
- adding installed components
- adding section on how to override values for install
Resolves https://github.com/projectriff/riff/issues/213
Resolves https://github.com/projectriff/riff/issues/161
> Updating Getting Started doc

- riff
- change the default for function version to be 0.0.1 instead of v0001
> Add a version command

- riff
- riff.bat
- the delete affects the resources and not their definitions
> Update the help texts for the delete command

- riff
- defaults to "default"
- needed for CI
> Add --namespace option

- samples/node/square/README.adoc
following the table in README
> Input | numbers
> Specify input

- config/delve/shell-function-invoker-debug.yaml
- samples/shell/echo/echo.sh
- samples/shell/wordcount/wordcount.sh
This should be merged along with https://github.com/projectriff/shell-function-invoker/pull/2.
> Switch samples to work with go shell-function-invoker

- samples/python/sentiments/README.adoc
- samples/python/sentiments/sentiments.py
> Rename sentiments-service.py to sentiments.py

- cli.go
- riff-cli/Makefile
- riff-cli/cmd/root.go
- riff-cli/global/riff_version.go
- adding ldflags option to build command to set the version
> Set CLI version using the VERSION file

- .travis.yml
Like https://travis-ci.org/projectriff/riff/builds/351431907
> Add labels for Travis dashboard

- Development-Helm-install.adoc
- Getting-Started.adoc
- helm-charts/README.adoc
- helm-charts/kafka/README.md
- helm-charts/riff/README.md
> Change "riffrepo" to "projectriff" in docs and READMEs

- function-controller/README.adoc
- function-sidecar/README.adoc
- helm-charts/README.adoc
- http-gateway/README.adoc
- topic-controller/README.adoc
> remove subdirectory ci badges, tweak descriptions

- helm-charts/riff/README.md
- helm-charts/riff/templates/http-gateway-deployment.yaml
- helm-charts/riff/values.yaml
> Adding httpHeadersWhitelist value to the Helm chart for riff

- Makefile
- config/service-account.yaml
- function-controller/Makefile
- http-gateway/Makefile
- topic-controller/Makefile
- also delete the invokers CRD on "make teardown"
> Move all riff components to riff-system for "make dev-setup"

- riff-cli/cmd/utils/command_utils.go
- riff-cli/docs/riff_create.md
- riff-cli/docs/riff_init.md
> Fix path in long description for init/create

- config/kafka/kafka.yaml
- function-controller/config/debug-service.yaml
- function-controller/config/deployment.yaml
- http-gateway/config/debug-service.yaml
- http-gateway/config/deployment.yaml
- http-gateway/config/service-nodeport.yaml
- topic-controller/config/debug-service.yaml
- topic-controller/config/deployment.yaml
> Make dev-setup resource names match a Helm chart install

- helm-charts/kafka/Chart.yaml
- helm-charts/kafka/templates/NOTES.txt
- helm-charts/kafka/templates/_helpers.tpl
- helm-charts/kafka/templates/kafka-deployment.yaml
- helm-charts/kafka/templates/kafka-service.yaml
- helm-charts/kafka/templates/zookeeper-deployment.yaml
- helm-charts/kafka/templates/zookeeper-service.yaml
- helm-charts/riff/templates/NOTES.txt
- helm-charts/riff/templates/_helpers.tpl
- helm-charts/riff/templates/function-controller-deployment.yaml
- helm-charts/riff/templates/http-gateway-deployment.yaml
- helm-charts/riff/templates/http-gateway-service.yaml
- helm-charts/riff/templates/rbac.yaml
- helm-charts/riff/templates/service-account.yaml
- helm-charts/riff/templates/topic-controller-deployment.yaml
- adding namespace to the template {{ defines }}
Fixes #478
> Helm add namespace to defines

- riff-cli/pkg/jsonpath/parser.go
> Return empty string on missing jsonpath

- helm-charts/riff/values.yaml
- can't have two top level `kafka` entries
> Move kafka.create to the proper yaml location

- helm-charts/riff/README.md
- helm-charts/riff/templates/NOTES.txt
- helm-charts/riff/templates/function-controller-deployment.yaml
- helm-charts/riff/templates/function-resource.yaml
- helm-charts/riff/templates/http-gateway-deployment.yaml
- helm-charts/riff/templates/http-gateway-service.yaml
- helm-charts/riff/templates/invoker-resource.yaml
- helm-charts/riff/templates/rbac.yaml
- helm-charts/riff/templates/service-account.yaml
- helm-charts/riff/templates/topic-controller-deployment.yaml
- helm-charts/riff/templates/topic-resource.yaml
- helm-charts/riff/values.yaml
- fix delete command in README
> Remove no longer needed crd and faas switches

- riff-cli/Makefile
- riff-cli/cmd/create.go
- riff-cli/cmd/init.go
- riff-cli/cmd/utils/command_utils.go
Fixes #502 
Fixes https://github.com/projectriff/riff/pull/518
> Override init and create usage template so that it uses "invoker" instead of "command".

- http-gateway/pkg/server/requests_handler.go
- http-gateway/pkg/server/requests_handler_test.go
- riff-cli/cmd/publish.go
- updating cli to add "Gateway Timeout" to make it easier to see the error vs 404
Fixes #533
> Changing to use "504 Gateway Timeout" for http-gateway timeouts

- http-gateway/cmd/http-gateway.go
- http-gateway/pkg/server/gateway.go
- http-gateway/pkg/server/messages_handler.go
- http-gateway/pkg/server/messages_handler_test.go
- http-gateway/pkg/server/requests_handler.go
- http-gateway/pkg/server/topic_existence_checker.go
> Introduce alwaysTrueTopicExistenceChecker

- riff-cli/cmd/invokers.go
- riff-cli/cmd/invokers_test.go
- riff-cli/cmd/version.go
- riff-cli/cmd/version_test.go
- riff-cli/cmd/wiring.go
- riff-cli/pkg/initializer/initializer.go
- riff-cli/pkg/invoker/operations.go
```bash
$ riff version
riff CLI version: 0.0.7-snapshot
COMPONENT             IMAGE
function-controller   projectriff/function-controller:0.0.7-snapshot
http-gateway          projectriff/http-gateway:0.0.7-snapshot
topic-controller      projectriff/topic-controller:0.0.7-snapshot
```
Refs #536
> Include riff component version in `riff version`

- function-sidecar/pkg/dispatcher/http/http.go
Function invokers using the http protocol do not need to be concerned
with the correlationId. It's confusing to invoker implementors because
they think they do need to handle and return this value.
The sidecar will set the correlationId on the http response from the
invoker, so the invoker has no influence over the value. It should not
be sent to the invoker, and any value from the invoker should be
ignored.
Fixes #531
> Remove corrlationId header from http protocol

- riff-cli/cmd/apply.go
- riff-cli/cmd/apply_test.go
- riff-cli/cmd/create_test.go
> Cleanup apply error message if no resources exist

- riff-cli/cmd/common_options.go
- riff-cli/cmd/init_test.go
> Allow artifact to be absolute or relative to $CWD

- function-proto/java/pom.xml
User can then optionally use the generated reactor API as well
as the native gRPC one. Also upgrades grpc and friends.
> Add reactor-grpc generator

- riff-cli/cmd/delete.go
- riff-cli/docs/riff_delete.md
> Fix delete example message

- cmd/commands/function.go
> Add command invoker to `riff function create`

- cmd/commands/cobra.go
- cmd/commands/system.go
- pkg/core/kubectl_client.go
- pkg/core/system.go
- change to y/N prompt
Fixes #660
> Add command interrupted message for system install/uninstall

- pkg/core/system.go
- make 'components' lowercase in all messages for consistency
> Split Istio install into crds and main file and wait 5s between

- pkg/core/function.go
- check for the observedGeneration
- check all status.conditions for Unknown state
Fixes #699
> Fix verbose output for failed function builds

- cmd/commands/function.go
> Don't use BroadcastXXValue when not necessary

- manifest.yaml
- pkg/core/fixtures/noistio.yaml
- pkg/core/fixtures/noknative.yaml
- pkg/core/fixtures/valid.yaml
- pkg/core/fixtures/wrongversion.yaml
- pkg/core/manifest.go
- pkg/core/system.go
Fixes https://github.com/projectriff/riff/issues/706
> Rename manifest version to manifestVersion

- manifest.yaml
- pkg/core/system.go
> Update stable manifest with latest eventing files

- cmd/commands/function.go
- cmd/commands/function_test.go
> Include namespace in function creation status hint if nondefault

- Makefile
- pkg/core/client.go
> Don't re-generate mocks when it's not needed

- pkg/core/service.go
> recognize nodeport for http or http2

- cmd/commands/image.go
- docs/riff_image_relocate.md
- pkg/core/fixtures/image_manifest/valid.yaml
- pkg/core/fixtures/image_manifest/wrongversion.yaml
- pkg/core/fixtures/image_relocation/image_manifest.yaml
- pkg/core/image.go
- pkg/core/image_manifest.go
- pkg/core/image_manifest_test.go
Fixes https://github.com/projectriff/riff/issues/765
> Change image manifest to contain a map rather than an array

- cmd/commands/service.go
- cmd/commands/service_test.go
- cmd/commands/wiring.go
- docs/riff_service.md
- docs/riff_service_revise.md
- pkg/core/annotations.go
- pkg/core/client.go
- pkg/core/function.go
- pkg/core/mocks/Client.go
- pkg/core/service.go
> Add `riff service revise` command

- cmd/commands/system.go
- docs/riff_system_install.md
- pkg/core/fixtures/manifest/absolutepath.yaml
- pkg/core/fixtures/manifest/invalidscheme.yaml
- pkg/core/fixtures/manifest/valid.yaml
- pkg/core/manifest.go
- pkg/core/manifest_test.go
- pkg/core/namespace.go
- pkg/core/system.go
Fixes https://github.com/projectriff/riff/issues/740
> riff system install support for manifests containing file paths

- cmd/commands/cobra.go
- cmd/commands/cobra_test.go
- cmd/commands/function.go
- cmd/commands/service.go
- docs/riff_function_create.md
- docs/riff_service_create.md
> Remove BroadcastStringValue

- cmd/commands/wiring.go
- docs/riff_system.md
- docs/riff_system_install.md
- docs/riff_system_uninstall.md
> Install kubeclient for system commands

- cmd/commands/wiring.go
- docs/riff_subscription.md
- docs/riff_subscription_create.md
- docs/riff_subscription_delete.md
- docs/riff_subscription_list.md
> Install kubeclient for subscription commands

- .gitattributes
See https://github.com/github/linguist#overrides
> Exclude vendor directory from github stats

- distro/commands/ginkgo_suite_test.go
- distro/commands/image.go
- distro/commands/image_test.go
- pkg/core/image_client.go
- pkg/core/image_client_test.go
> Replace check flag with no-check for riff-distro image list

- cmd/commands/service.go
- cmd/commands/service_test.go
- cmd/commands/subscription.go
> Make service list rely on generic display function

- distro/README.md
> README for riff-distro

- cmd/commands/image.go
- docs/riff_image.md
- docs/riff_image_load.md
- docs/riff_image_push.md
- docs/riff_image_relocate.md
Fixes https://github.com/projectriff/riff/issues/893
> Clarify docs for riff image push/load

- pkg/core/image.go
- pkg/core/image_mapper.go
Fixes https://github.com/projectriff/riff/issues/889
> Make imageMapper map a single image.Name directly

- pkg/core/function.go
- seems to be a timing issue
Fixes #922
> Retry the status for build errors

- pkg/core/system.go
> Add delete of "horizontalpodautoscaler.autoscaling/istio-pilot" resource

- pkg/core/system.go
> Add 5 sec sleep before retrying applying resources

- cmd/commands/function.go
- cmd/commands/function_test.go
- docs/riff_function_create.md
> Remove the --builder flag

- main.go
- istio to `v20181106-v0.2.0-26-g91cd00d` of serving
- serving to `v20181106-v0.2.0-26-g91cd00d`
> Update "stable" to latest serving release-0.2 branch artifacts

- main.go
- istio to `v0.2.2` of serving
- serving to `v0.2.2`
> Update "stable" to serving v0.2.2 artifacts

- pkg/core/function.go
Fixes https://github.com/projectriff/riff/issues/961
> [WIP - DO NOT MERGE] Make function update use the same --no-pull strategy as function create

- .travis.yml
- Makefile
> Check commited docs are up-to-date

- pkg/core/system.go
> Add removal of "knative-ingressgateway" to "system uninstall"

- .travis.yml
* WIP
* This is connected to #1001
> Run unit tests on Windows as part of CI build

- cmd/commands/function.go
- cmd/commands/function_test.go
- cmd/commands/wiring.go
- pkg/core/client.go
- pkg/core/function.go
- pkg/core/function_test.go
- pkg/core/mocks/Client.go
> Extract builder from Knative/K8s-related interface

- Private-Registry-for-Images.md
> Add doc for "Using a Private Registry for Images"

- .travis.yml
- Makefile
- README.adoc
and cleanup whitespace
Follow up to #1029
> Drop references to dep

- go.mod
- go.sum
- main.go
See https://github.com/knative/serving/releases/tag/v0.2.3
> Upgrade to Knative Serving 0.2.3

- pkg/core/function.go
- pkg/core/function_test.go
> Fail if service with same name as the function to be created exists

- .travis/fats.sh
> Restore local builds in acceptance tests (#1043)

- cmd/commands/namespace.go
- cmd/commands/system.go
- cmd/commands/system_test.go
> Require --manifest if no default is set

- pkg/core/system.go
Simply repeats every 5 seconds and gives up after 5 minutes. Exponential
backoff, for example, is not suitable as the chance of success does not reduce
over time.
Fixes: https://github.com/projectriff/riff/issues/987
> Increase retries of system install steps

- cmd/commands/service.go
- cmd/commands/service_test.go
> Print response status only for 4xx and 5xx codes

- pkg/core/fixtures/local-yaml/buildtemplate.yaml
- pkg/core/fixtures/local-yaml/manifest.yaml
- pkg/core/namespace.go
- pkg/core/namespace_test.go
Fixes https://github.com/projectriff/riff/issues/1107
> namespace init support for manifest with local yamls

- pkg/core/system.go
> Include delete of mutatingwebhookconfiguration with "istio-" prefix

- pkg/core/system.go
- all other messages use lower case
> Make message for deleting Knative services consistent

- .travis/fats-fetch.sh
- .travis/fats.sh
- better errors when installing a tool fails
> Pull in the lastest FATS

- cmd/commands/wiring.go
- pkg/fileutils/paths.go
- pkg/fileutils/paths_test.go
- pkg/kubectl/kubectl.go
> Pass configuration overrides to kubectl shellout

- .travis/fats-fetch.sh
- .travis/fats.sh
Function source is now co-located in the FATS repo.
Refs https://github.com/projectriff/fats/commit/6ee8b97d8f0d9cf868a05bebe62a729a6ddde99b
> Update FATS to latest

- cmd/riff/main.go
> Upgrade Knative Serving to 0.5.0

- cmd/riff/main.go
> Update Knative Build to v0.5.0

- pkg/core/client.go
- pkg/core/helpers.go
- pkg/core/namespace.go
- pkg/core/namespace_test.go
>  Delete existing image prefix when none set

- Using-Registries.md
> Update registries doc

- pkg/core/client.go
- pkg/core/helpers.go
- pkg/core/namespace.go
- pkg/core/namespace_test.go
It might contain other values, instead zero out the value we want to
remove.
Follow up to #1205
> Avoid deleting the configmap

- cmd/riff/main.go
> Use the 0.2.0 builder

- go.mod
- go.sum
> update to latest go-ape

- azure-pipelines.yml
- ci/unit-test-steps.yml
- pkg/core/kustomize/kustomize_test.go
- pkg/core/manifest_test.go
- pkg/core/namespace_test.go
> Fix tests on Windows

- azure-pipelines.yml
- ci/fats-channels.sh
- ci/fats.sh
- ci/install-gcloud.yml
For full FATS jobs, also tests on Windows targetting a GKE cluster.
Refs #1174
> Add Windows FATS tests

- pkg/riff/commands/credential_delete_test.go
- pkg/riff/commands/credential_list_test.go
- pkg/riff/commands/credential_set_test.go
- pkg/riff/commands/credential_test.go
- pkg/riff/commands/function_create_test.go
- pkg/riff/commands/function_delete_test.go
- pkg/riff/commands/function_list_test.go
- pkg/riff/commands/function_test.go
- pkg/riff/commands/requestprocessor_create_test.go
- pkg/riff/commands/requestprocessor_delete_test.go
- pkg/riff/commands/requestprocessor_list_test.go
- pkg/riff/commands/root_test.go
- pkg/testing/command_table.go
- pkg/testing/options_table.go
The minor perf improvement isn't worth the noisy output.
> Drop test parallelization

- docs/riff_handler_create.md
- pkg/cli/flags.go
- pkg/parsers/env.go
- pkg/riff/commands/handler_create.go
- pkg/riff/commands/handler_create_test.go
- pkg/validation/env.go
- MY_VAR_FROM_CONFIGMAP=configMapKeyRef:my-configmap:my-key
- MY_VAR_FROM_SECRET=secretKeyRef:my-secret:my-key
> Restore env support from secrets and configmaps

- azure-pipelines.yml
- ci/downgrade-docker.yml
- ci/duffle-creds/k8s.yaml
- ci/fats-cleanup.sh
- ci/fats-fetch.sh
- ci/fats.sh
FATS is updated to use the CNAB bundle via duffle and the new riff cli
Like #1297 but restores FATS and FATS light.
> Restore FATS

- go.mod
- go.sum
- pkg/riff/commands/application_list.go
- pkg/riff/commands/application_list_test.go
- pkg/riff/commands/function_list.go
- pkg/riff/commands/function_list_test.go
- change primary condition from Succeeded to Ready for Application and
Function
> Consume latest riff-system

- azure-pipelines.yml
- ci/downgrade-docker.yml
- ci/fats.sh
also use Docker Hub since it's so much faster and we have credentials
> Run all functions for full FATS runs

- go.mod
- go.sum
- pkg/k8s/wait.go
For example if you create a function without --image and no default
image prefix is set you will see:
```
Created function "my-function"
Error: failed to become ready: missing default image prefix
```
Resolves #1300
Depends on https://github.com/projectriff/system/pull/29
> Stop wait and show an error when resource ready condition turns false

- rfc/rfc-0003-developer-utils.md
> rfc-0003: A pod with utilities for better developer experience

- rfc/rfc-0004-default-ingress-policy.md
> RFC 0004: Default Ingress Policy

- rfc/rfc-0006-child-resource-names.md
Comments due by Friday, December 6th
> RFC 0006: Guidance for child resource names

- rfc/rfc-0007-resource-references.md
Comments due by Friday, December 6th
> RFC 0007 Guidance for resource references

- rfc/rfc-0008-pod-templates.md
Comments due by Monday, December 9th.
> RFC 0008: Pod Templates

- rfc/rfc-0011-streaming-gateways.md
Comments are open until Thursday, January 16th.
> RFC 0011: Streaming Gateways

- rfc/rfc-0010-drop-core-runtime.md
Feedback is open until Tuesday, January 14th
> RFC 0010: Drop core runtime
