config/topic-gateway-service-nodeport.yaml
otherwise the port may be already allocated in case of multiple deployments, as seen here: https://ci.faas.to.cf-app.com/teams/pfs/pipelines/faas_integration/jobs/build-sk8s-and-invoker-java/builds/25
=> allow k8s to generate random nodePort

helm/values-nodeport.yaml, helm/values-snapshot.yaml
- use values-nodeport.yaml for overriding service type of LoadBalancer with NodePort
- use values-snapshot.yaml for overriding riff component tag with SNAPSHOT build tags
- install using `helm install --name demo --values helm/values-snapshot.yaml,helm/values-nodeport.yaml riffrepo/riff`
=> Add values files to override provided values for Helm install

config/function-controller-deployment.yaml, config/http-gateway-deployment.yaml, config/topic-controller-deployment.yaml, helm/values-snapshot.yaml, samples/slack/slack-command/Dockerfile
- Dockerfiles for samples all use 0.0.1 function invoker base images
- local config yaml for riff components all use 0.0.2-snapshot
- the values-snapshot.yaml used local helm install overrides also uses 0.0.2-snapshot
=> updates after 0.0.1 release

build-java-function-invoker
Previously, the java-function-invoker would take over 2 minutes to
build. After skipping tests, the build time drops to ~10 seconds.
Tests should be run at dev time and in CI, but are not needed at deploy
time.
=> Skip tests when building the java function invoker

Makefile, README.adoc, message-transport/README.adoc
For now, we require two similar env vars to be set. This can be cleaned up
later, applying due care to avoid breaking CI.
Also fix a couple of typos.
Implements https://github.com/projectriff/riff/issues/374
=> Cascade tests from the top

function-sidecar/Makefile, http-gateway/Makefile, message-transport/Makefile, riff-cli/Makefile, topic-controller/Makefile
Now that we have cascading tests, verbosity is distracting.
=> Make default test output less verbose

samples/README.adoc
* sentiments doesn't exist, and concat and upper are not mentioned.  Removed sentiments and added concat/upper.  Fixes #411
=> Fix python samples links

riff-cli/cmd/completion.go, riff-cli/cmd/invokers.go, riff-cli/cmd/invokers_test.go, riff-cli/cmd/wiring.go, riff-cli/docs/riff.md, riff-cli/docs/riff_invokers.md, riff-cli/docs/riff_invokers_apply.md, riff-cli/docs/riff_invokers_delete.md, riff-cli/docs/riff_invokers_list.md, riff-cli/pkg/kubectl/kubectl.go, riff-cli/pkg/kubectl/mock_KubeCtl.go, riff-cli/pkg/osutils/osutils.go
$ riff invokers list
NAME      VERSION
command   0.0.6-snapshot
go        0.0.2-snapshot
java      0.0.6-snapshot
node      0.0.6-snapshot
python2   0.0.6-snapshot
python3   0.0.6-snapshot
$ riff invokers apply
invoker "command" configured
invoker "go" configured
invoker "java" configured
invoker "node" configured
invoker "python2" configured
invoker "python3" configured
$ riff invokers apply -f node-invoker.yaml
invoker "node" configured
$ riff invokers apply -f https://github.com/projectriff/node-function-invoker/raw/master/node-invoker.yaml
invoker "node" configured
$ riff invokers apply -f node-invoker.yaml --name node8
invoker "node8" configured
$ riff invokers apply -f node-invoker.yaml --version latest
invoker "node" configured
$ riff invokers delete node8
invoker "node8" deleted
$ …
=> `riff invokers` commands

Makefile
Create namespace is the only command that is not idempotent. Ignore failures
=> Make it so that make dev-setup can be run multiple times

riff-cli/Makefile, riff-cli/pkg/initializer/initializer.go
The RIFF_INVOKER_PATHS env var can specify a comma separated list of
paths to invoker.yaml files. When specified, no attempt will be made to
load invokers from kubectl.
Refs: #454
=> Override kubectl invoker lookup with RIFF_INVOKER_PATHS

riff-cli/cmd/create_test.go, riff-cli/pkg/initializer/initializer.go, riff-cli/test_data/invokers/python2-function-invoker.yaml, riff-cli/test_data/invokers/python3-function-invoker.yaml, riff-cli/test_data/riff-init/matching-invoker-with-output-topic/Dockerfile, riff-cli/test_data/riff-init/multiple-matching-invokers-with-one-selected-no-artifact/Dockerfile, riff-cli/test_data/riff-init/multiple-matching-invokers-with-one-selected/Dockerfile
A handler's config in an Invoker resources can be:
```yaml
handler:
default: "{{ .TitleCase .FunctionName }}"
description: the name of the function handler (name of Exported go function)
```
Issue: #427
=> Add .TitleCase method to handler value template

Development-Helm-install.adoc, Getting-Started.adoc, helm-charts/riff/Chart.yaml, helm-charts/riff/README.md, helm-charts/riff/requirements.lock, helm-charts/riff/requirements.yaml, helm-charts/riff/values.yaml
- set projectriff/kafka dependency to version `0.0.2`
- new flag to turn on the kafka install: `--set kafka.create=true` (default is false, so this makes it opt-in as suggested)
- this eliminates the separate transport release
- changing the release name to be projectriff instead of control
- updating Getting-Started and Development-Helm-install docs
Fixes: #477
=> Add kafka chart as a conditional dependency to riff chart

helm-charts/riff/templates/_helpers.tpl, helm-charts/riff/templates/function-controller-deployment.yaml, helm-charts/riff/templates/http-gateway-deployment.yaml, helm-charts/riff/templates/topic-controller-deployment.yaml, helm-charts/riff/values.yaml
- will use release name as part of default
- can be overridden by `kafka.broker.nodes` and `kafka.zookeeper.nodes` values
Fixes #506
=> Create helper template functions for kafka and zookeeper nodes

riff-cli/cmd/init.go, riff-cli/cmd/utils/command_utils.go, riff-cli/test_data/docs/riff_create_command.md, riff-cli/test_data/docs/riff_init_command.md
When using cobra to set the default value for the --invoker-version flag
for `riff init <invoker>` and `riff create <invoker>` the wrong default
version can be selected at runtime.
Previously, we used the list of invokers to dynamically install sub
commands for `init` and `create`. The default for the invoker version
was set based on the invoker version. With a set of invokers installed
like:
```
NAME      VERSION
command   0.0.6-snapshot
go        0.0.2-snapshot
java      0.0.6-snapshot
node      0.0.6-snapshot
python2   0.0.6-snapshot
python3   0.0.6-snapshot
```
When creating a function with the go invoker, cobra is defaulting the
.InvokerVersion to `0.0.6-snapshot`, instead of the `0.0.2-snapshot`.
When the go invoker is the only invoker install, it defaults correctly
to …
=> Avoid defaulting the invoker version

riff-cli/cmd/create_test.go, riff-cli/cmd/init.go, riff-cli/cmd/init_test.go, riff-cli/pkg/initializer/initializer.go
riff will no longer attempt to resolve an invoker based on the files in
the current directory. The previous resolution could change behavior as`
new invokers are installed in the cluster or files change on disk.
Fixes #502
=> Require an invoker be specified for init and create commands

Development-Helm-install.adoc
- including minikube command that uses `--bootstrapper=localkube`
=> Adding bootstrapper note

README.adoc
@dsyer suggested that it would be helpful to link to the samples. This is a step in that direction while still acknowledging that 3rd parties can write invokers which are just as valid as those provided in the riff project.
=> Link to invoker repos for samples

http-gateway/cmd/http-gateway.go, http-gateway/pkg/server/riff_topic_existence_checker.go
You only need to be paranoid about topic existence if you are running
in an actual cluster. Running locally (like it says you can do in the
docs) there is no need to check for topic existence in k8s because
there is no k8s.
=> Make k8s resource checks in http gateway optional

function-sidecar/cmd/function-sidecar.go, http-gateway/cmd/http-gateway.go
For optional io.Closer implementations, it's cleaner to test for io.Closer
before deferring the close.
=> Adopt a common way of deferring close

function-controller/pkg/controller/deployer.go, function-controller/pkg/controller/deployer_test.go
There are two different protocols the function sidecar can use to
communicate with the function invoker: http and grcp. Previously, the
invoker had no way to know how it would be invoked, so the invoker
needed to setup a server to receive traffic for each protocol.
The configured function sidecar to invoker protocol is now set in the
function invoker pod as the RIFF_FUNCTION_INVOKER_PROTOCOL env var.
Refs projectriff/java-function-invoker#73
=> Expose function sidecar protocol to the invoker

riff-cli/cmd/create.go, riff-cli/cmd/init.go
`riff create <invoker> <filepath>` is also handled as
`riff create <invoker> --filepath <filepath>`. Previously, the equivlent
with `riff init` was also not true. Now the first argument is treated
uniformly as the filepath flag for both the init and create commands.
Issue: #488
=> Align init and create command args

Makefile, README.adoc, config/namespace/riff-system.yaml, config/rbac/riff-cluster-rolebinding.yaml, config/rbac/riff-clusterrole.yaml, config/rbac/riff-role.yaml, config/rbac/riff-rolebinding.yaml, config/service-account.yaml, function-controller/config/deployment.yaml, http-gateway/config/deployment.yaml, topic-controller/config/deployment.yaml
- update cluster role
- change the way riff-system namespace is created
- make http-gateway use the riff service account
- change service account, role and rolebinding names to match Helm install
=> Fix RBAC issues and enable it by default

glide.lock, glide.yaml, riff-cli/cmd/create.go, riff-cli/cmd/create_test.go, riff-cli/cmd/init.go, riff-cli/cmd/init_test.go, vendor/github.com/spf13/pflag/bytes.go, vendor/github.com/spf13/pflag/bytes_test.go, vendor/github.com/spf13/pflag/count.go, vendor/github.com/spf13/pflag/count_test.go, vendor/github.com/spf13/pflag/duration_slice.go, vendor/github.com/spf13/pflag/duration_slice_test.go, vendor/github.com/spf13/pflag/flag.go, vendor/github.com/spf13/pflag/flag_test.go, vendor/github.com/spf13/pflag/golangflag.go, vendor/github.com/spf13/pflag/golangflag_test.go, vendor/github.com/spf13/pflag/int16.go, vendor/github.com/spf13/pflag/printusage_test.go, vendor/github.com/spf13/pflag/string_array.go, vendor/github.com/spf13/pflag/string_slice.go
Ignore unknown falgs for init and create commands  …
If the user attempts to run a command like:
riff create java --handler functions.Uppercase
...but they do not have the java invoker installed, they currently
recieve an unhelpful error saying the `--handler` flag is unknown. Since
the init and create root comamnds require an invoker, and some invokers
require the handler flag while others do no, we can relax the
enforcement of unknown flags for these commands. Subcommands continue to
enforce unknown flags.
The ability to supress unknown flag warnings is new in pflags v1.0.1.
Fixes #555
=> Unknown flags

http-gateway/cmd/http-gateway.go, http-gateway/pkg/server/gateway_integration_test.go, http-gateway/pkg/server/messages_handler.go, http-gateway/pkg/server/messages_handler_test.go, http-gateway/pkg/server/requests_handler.go, http-gateway/pkg/server/requests_handler_test.go, http-gateway/pkg/server/topic_existence_checker.go
The issue reported at projectriff/riff#553 showed that topic checking introduced a performance regression of 2 orders of magnitude. This renders the s1p sample unusable. The commits in this PR change the implementation to use a callback-with-cache mechanism provided by Kubernetes APIs (shared informers).
To validate performance improvement, I compared the `alwaysTrueTopicExistenceChecker` and `RiffTopicExistenceChecker` using `ab2`. Not very scientific, but a useful sanity check. My test case shows the two checking strategies now perform approximately identically, suggesting they are hitting some bottleneck unrelated to topic lookup.
```
ab -H "Content-Type: text/plain" -n 100000 -c 100 -p in.txt http://192.168.39.8:30788/requests/numbers
...
Concurrency Level:      100
Time taken for …
```
=> Repair 404 performance regression by using a shared TopicInformer

riff-cli/cmd/version.go, riff-cli/cmd/version_test.go
```bash
$ riff version
riff CLI version: 0.0.7-snapshot
kubectl context: docker-for-desktop
COMPONENT             IMAGE
function-controller   projectriff/function-controller:0.0.7-snapshot
http-gateway          projectriff/http-gateway:0.0.7-snapshot
topic-controller      projectriff/topic-controller:0.0.7-snapshot
INVOKER   VERSION
java      0.0.6
node      0.0.9-snapshot
```
=> Add kubectl current-context to `riff version`

riff-cli/pkg/osutils/osutils.go
Looks like some gofmt changes snuck in here, lemme know if you want that split out or removed.
This might have some negative consequences if there are any programs that are being shelled out to that put their error messages on *stdout* instead of *stderr*, but at least for kubectl this fixes the problem.
Fixes #522
=> Fix error messages when deleting a function that doesn't exist

function-controller/pkg/controller/deployer.go, function-controller/pkg/controller/deployer_test.go, function-sidecar/cmd/function-sidecar.go, function-sidecar/pkg/carrier/carrier_integration_test.go, function-sidecar/pkg/dispatcher/http/http.go
The port used for the function sidecar to communicate with the function
invoker is currently shared knowledge. Each invoker needs to know to
listen on 8080 for http or 10382 for grpc. This knowledge is hard coded
into the sidecar and each function invoker.
Instead the ports should be determined by the function-controller and
set into the function's deployment. For the sidecar there is a new
`--port` argument, and for the invoker there are environment variables
`HTTP_PORT` and `GRPC_PORT`.
There are two port variables for the invoker because there are cases
where an invoker may need to support http and grpc.
These ports should no longer be hard coded in invokers. Although the
values have not changed.
=> Parameterize ports between invoker and sidecar

function-sidecar/cmd/function-sidecar.go
Fixes #572 without requiring initial delay.
=> Change to fined grained fixed backoff for 60 sec. 

riff-cli/cmd/delete.go, riff-cli/cmd/delete_test.go
Fixes #530  -  Also fixed `delete --all -n no_exist`  did not print the error msg. (#522 works if `--all` not set.)
=> Delete function if topics don't exist

config/rbac/riff-clusterrole.yaml, function-controller/cmd/function-controller.go, function-controller/config/deployment.yaml, function-controller/pkg/controller/deployer.go, function-controller/pkg/controller/deployer_test.go, helm-charts/riff/templates/function-controller-deployment.yaml, helm-charts/riff/templates/rbac.yaml
Support is provided by enabling a feature flag BEFORE the function controller is
deployed. The feature flag is enabled by setting the property
stream-gateway=enabled in the riff-feature-flags configmap in the riff-system
namespace.
For example, the feature flag may be enabled as follows:
```
kubectl create configmap riff-feature-flags --from-literal=stream-gateway=enabled --namespace=riff-system
```
When the feature flag is enabled:
* A service is created for each link which fronts the gRPC servers of the link's
function pods
* The function pod consists of the main container only (with no function sidecar)
=> [DNM] Support stream gateway in function controller

function-sidecar/cmd/function-sidecar.go, function-sidecar/pkg/dispatcher/grpc/grpc.go, function-sidecar/pkg/dispatcher/grpc/grpc_test.go
Allows embedding several instances of dispatcher.
=> Extract reading of windowing config out of NewGrpcDispatcher()

cmd/commands/service.go, pkg/core/service.go
an ingress can be defined as either an IP address or a hostname. For
example, EKS uses ELB hostnames rather than IP addresses.
=> Handle ingress hostnames in addition to IPs

README.adoc
Until @projectriff has its own homebrew tap and debian repo, I've
got our CI building them off riff/releases.
E.g. https://ci.starkandwayne.com/teams/main/pipelines/homebrew-recipes/jobs/riff-homebrew
=> Download riff cli from homebrew or debian

cmd/commands/system.go, cmd/commands/wiring.go, docs/riff_system.md, docs/riff_system_install.md, docs/riff_system_uninstall.md, pkg/core/kubectl_client.go, pkg/core/namespace.go, pkg/core/service.go, pkg/core/system.go
- update to use latest Istio and Knative resources for 0.1.1
- don't overwrite existing Istio installation
- add new checks for install/uninstall to make sure namespaces aren't terminating
- check that namespaces exist before uninstalling
- make Istio uninstall optional
- add --force flag to install/uninstall to avoid prompts
- labeling namespaces no longer needed
- change to use fmt.Printf instead of print
Fixes #625
=> Add "system uninstall" command and update Knative/Istio

cmd/commands/function.go, cmd/commands/function_test.go, cmd/commands/service.go, cmd/commands/service_test.go, cmd/commands/shared.go, docs/riff_function_create.md, docs/riff_service_create.md, pkg/core/env_var.go, pkg/core/env_var_test.go, pkg/core/function.go, pkg/core/ginkgo_suite_test.go, pkg/core/service.go
- the env vars are provided in a `key=value` format for `--env` flag
- also supports valueFrom expressions using `--env-source` flag
- supported sources for now are configMapKeyRef and secretKeyRef
example for configMapKeyRef:
--env-source MYSQL_USER=configMapKeyRef:petclinic-config:mysql-user
example for secretKeyRef:
--env-source MYSQL_PASSWORD=secretKeyRef:petclinic-db-mysql:mysql-root-password
FIXES #649
=> Add the option to provide env vars to services and functions

pkg/core/manifest.go, pkg/core/system.go
Include version as part of constant name.
Don't export it until it's actually needed.
=> Don't use ALL_CAPS for constant.

.travis.yml
Fixes the current build condition (not sure how it did not fail before)
and also prevent the makefile from messing with a user's installation
without her consent
=> Install mockery as part of travis

cmd/commands/image.go, cmd/commands/namespace.go, cmd/commands/system.go, docs/riff_image_relocate.md, docs/riff_namespace_init.md, docs/riff_system_install.md, pkg/core/image.go, pkg/core/manifest.go, pkg/fileutils/dir.go, pkg/fileutils/dir_test.go, pkg/fileutils/doc.go, pkg/fileutils/fileutils_suite_test.go, pkg/fileutils/fixtures/file.txt, pkg/fileutils/read.go, pkg/fileutils/read_test.go
This applies to the following commands:
* namespace init
* image relocate
* system install
Fixes https://github.com/projectriff/riff/issues/770
=> Allow manifest on namespace init and other commands to be URL

cmd/commands/wiring.go, main.go
=> Make the full Help message appear when there is an error, rather than Usage.

cmd/commands/channel.go, cmd/commands/function.go, cmd/commands/shared.go, docs/riff_function_create.md
Fixes #800
Remove no longer needed constants.
=> Remove vestigial reference to channels in `riff function create`.

manifest.yaml, pkg/core/manifest.go
While we wait for a serving release with an updated build, we should all be testing against this version of knative.
=> Bump stable manifest to latest releases

manifest.yaml, pkg/core/manifest.go
- update stable and latest manifests to point to build-template with cache enabled
- a PersistentVolumeClaim named riff-build-cache is created in the namespace
- this requires that a default StorageClass is defined
- both GKE and Minikube has a `standard` class as the default
- the claim is for 8Gi
=> Enable namespace cache for buildpack builds

manifest.yaml, pkg/core/manifest.go
Lock in manifest versions for pre-release validation
=> Prepare release v0.1.3

cmd/commands/function.go, cmd/commands/function_test.go, docs/riff_function_create.md
As referenced in https://github.com/projectriff/riff/issues/634, as a possible solution for greater invoker flexibility...
While working on/testing an update to the python invoker, adding a custom flag definitely made my life easier. 
This still maintains the 'riff function create INVOKER FUNCTION_NAME  [flags]' pattern but adds a 'custom' type that requires the '-invoker-url' flag.
=> Add custom '--invoker-url' to function create

manifest.yaml, pkg/core/manifest.go
Build can now be released independently of serving, we will no longer
need serving to update the build release for us.
Fixes #870
=> Bump stable manifest versions

Community-Releases.adoc, README.adoc
- clarifed introductory paragraph and knative developer install paragraph
- moved "community releases" to separate page
- added section at the end for riff-distro
Preview [here](https://github.com/jldec/riff/blob/d91694132f15191eabf5b7b8af89b4f3a14852b8/README.adoc)
=> Clarify README

manifest.yaml, pkg/core/function.go, pkg/core/manifest.go
Function create fails unless we ignore the "scale to zero" status message that we now see between the build and the revision being ready
Fixes #907 
Fixes #908
=>  Update to artifacts from v20181029

cmd/commands/function.go
When diving into riff it was a bit unclear where local-source could be used. 
A bit of explanation would go a long way. 😄
=> Add explanatory local path help text

main.go
- istio to v0.2.0 of serving
- build to v0.2.0
- serving to v0.2.0
- eventing to v20181031-a2f9417
Fixes #919
=> Update "stable" to latest releases

main.go, pkg/core/function.go
- removed the hack for "scaled to zero" failure message
- update stable to use `v20181101-v0.2.0-11-g877523d` release for serving
- the `v20181101-v0.2.0-11-g877523d` serving release includes fix (https://github.com/knative/serving/pull/2348) for status transitions
Fixes #922
=> Restore the function wait/verbose functionality

distro/commands/distro.go, distro/commands/wiring.go, distro/docs/riff-distro.md, distro/docs/riff-distro_create.md, pkg/core/image.go, pkg/core/image_client.go, pkg/core/image_test.go, pkg/core/mocks/ImageClient.go, pkg/docker/docker.go, pkg/resource/list.go
`riff-distro create` downloads a manifest and its configuration files, scans
the files for images, downloads the images, and then creates a distribution
archive from the various downloads.
=> Distribution creation

configuration.go, docs/riff_function_create.md, pkg/core/function.go
Expose artifact and handler as BuildTemplate parameters
Fixes #905
=> Make the 'command' & node languages use buildpacks

configuration.go
The legacy Knative eventing CRDs are being removed from the repo. We'll need to pin to this version until we rebase onto the new CRDs.
=> Pin Knative eventing "latest"

pkg/core/function.go, pkg/core/function_test.go
* Add 10 minute timeout to avoid blocking forever
* Split helper functions out of waitForSuccessOrFailure
* In verbose mode, log progress of waiting
* Add unit test of polling loop
* Modify LatestCreatedRevisionName logging to avoid interleaving
=> Refactor and improve function wait code

pkg/core/function.go
The RUN_IMAGE is defaulted within the riff-cnb buildtemplate. We should
never overwrite that default with an empty value.
=> Don't overwrite an empty run image

pkg/core/system.go
If pods are slow to be created there may not immediately be pods that
exist to check if they are running. Previous, this would pass the test.
Now we require there be at least three pods in the namespace.
Additionally, we wait 10 seconds before the first test, rather than
testing immediately.
=> Ensure there are pods in the istio-system namespace

pkg/core/fixtures/manifest/absolutepath.windows.yaml, pkg/core/manifest.go, pkg/core/manifest_test.go, pkg/core/namespace_test.go, pkg/fileutils/copier_test.go, pkg/fileutils/dir.go, pkg/fileutils/dir_test.go, pkg/fileutils/read.go, pkg/fileutils/read_test.go, pkg/test_support/file_operations.go
* To disambiguate a string which could be either a file path or a URL,
check for it being an absolute file path first in order to cope with
Windows paths that look like URLs.
* Remove the leading slash of the path of a file URL on Windows when
converting the URL into a file path. This is a known issue with Go.
* Skip symlink tests when symlinks cannot be created since, on some
versions of Windows, creating symlinks needs administrator
privileges.
* Tolerate behaviour when creating files on Windows: the permissions
specified are not honoured.
=> Make unit tests pass on Windows

.travis/fats-channels.sh, .travis/fats-fetch.sh, .travis/fats.sh
The stub bus no longer exists, there is now an in-memory-channel cluster channel provisioner
=> Update FATS ready checks for Knative eventing 0.2

.travis.yml, .travis/fats.sh, .travis/publish.sh, .travis/stage.sh
- stage cli release after unit tests pass
- use staged cli build in fats
- promote cli release after fats passes
```
gs://projectriff/riff-cli/releases/latest/*
gs://projectriff/riff-cli/releases/$(cat VERSION)/*
gs://projectriff/riff-cli/releases/builds/$(cat VERSION)-$(git rev-parse HEAD)/*
```
Fixes #1031
=> Publish riff cli snapshots

.travis/fats-channels.sh, .travis/fats-cleanup.sh, .travis/fats-fetch.sh, .travis/fats.sh
Also run `riff system uninstall` which we always should have been doing.
=> Fold log output for FATS

README.adoc
Go changed its checksum algorithm recently and anyone building with 1.11.2 or
earlier will hit checksum mismatches.
=> Require Go 1.11.4 or later

pkg/fileutils/read.go
A situation which currently panics is legitimate and so should be diagnosed using an error. For example under Git Bash on Windows:
riff namespace init ... --manifest file:///C:\somedir\manifest.yaml
currently results in:
panic: readAbsFile called with relative file path: C:somedirmanifest.yaml
because the backslashes are treated as Bash escape characters.
The diagnostics will now be:
Error: Error reading manifest file: absolute path expected instead of relative path: C:somedirmanifest.yaml
Fixes https://github.com/projectriff/riff/issues/1007
=> Return an error instead of panicking

docs/riff_namespace_init.md, docs/riff_system_install.md, main.go
There are three built-in manifests:
- nightly: nightly knative builds from master
- latest: most recent knative release
- stable: blessed and tested knative releases
=> Add nightly manifest

cmd/commands/function.go, cmd/commands/function_test.go, pkg/core/function.go
The CLI now saves info required for riff.toml in annotations in
the ksvc, to be later used by `riff function update`.
Some refactoring of the local build code to make it more atomic.
Fixes #1055
=> riff function update works (again) with local-path

Makefile
=> Normalize backslashes mock paths for Windows

pkg/core/function.go
... rather than hard-coded default
Fixes https://github.com/projectriff/riff/issues/1081
=> For in-cluster builds, use RUN_IMAGE from build template

main.go, pkg/core/function.go
A ClusterBuildTemplate has the advantage of being defined once in the
cluster and can be updated and maintained with the rest of riff.
The cache PVC has moved into a separate resource as it and a service
account are still required in each namespace in order to run builds.
Fixes #968
=> Use a cluster BuildTemplate

.travis.yml
This afternoon, [Travis started](https://changelog.travis-ci.com/go-modules-support-added-for-go-1-11-and-up-88993) to set `GO111MODULES=on` for projects with golang 1.11 and a `go.mod` file. This causes mockery to fail to install. We can get mockery installing again, by turning modules back off for that command.
=> Disable go modules when installing mockery

.travis.yml
I have no faith that Travis Windows builds will ever actually work.
Right now they spin for ~14 minutes before failing. We don't need
consume resources for something we know will fail.
=> Remove Windows tests on travis

main.go
There should be no change in functionality, this is a refactoring of
riff-buildpack to decompose into individual function buildpacks.
Refs #1093
=> Consume decomposed function buildpack builder

go.mod, go.sum, pkg/core/annotations.go, pkg/core/function.go, pkg/core/function_test.go, pkg/core/service.go
- due to changes in Knative Serving we need to add a full Build as an Unstructured object
- we can then annotated the Build instead of the Revision to trigger a build
- this is necessary after the changes in https://github.com/knative/serving/pull/2402
Fixes #939
=> Change the way builds are annotated

main.go, pkg/core/function.go
The build template now defaults the cache to an empty dir, individual
builds may define their own volume and define the CACHE argument to use
that volume.
This behavior makes the build template more useable, since it no longer
requires as PVC, and preserves the current cache behavior.
Depends on https://github.com/projectriff/riff-buildpack-group/pull/36
=> Provide a cache volume for builds

cmd/commands/function.go, cmd/commands/function_test.go, docs/riff_function_create.md, pkg/core/function.go
Builds can now be triggered from directories nested in a git repo. This
means that a single repo can host multiple functions. Only files within
the path will exist at build time.
```
riff function create <name> --git-repo <repo> --sub-path path/within/repo
```
Fixes #1089
=> Allow builds from directories within git repos

cmd/commands/cobra.go, cmd/commands/namespace.go, cmd/commands/namespace_test.go, docs/riff_namespace_init.md, pkg/core/namespace.go, pkg/core/namespace_test.go
The --registry-host and --registry-protocol fields are hopelessly
entangled. We can provide a better user experiance by combining them
into a single flag named --registry.
Fixes #1140
=> Merge --registry-host and --registry-protocol

Makefile
./main.go is a symlink to ./cmd/riff/main.go, it's intended as a fall
back, but not the main entry point. We should use the proper entry point
when building riff.
Refs #1155
=> Use proper main location for building riff

function-proto/java/mvnw, function-proto/java/mvnw.cmd, function-proto/java/pom.xml, vendor/github.com/googleapis/gnostic/COMPILE-PROTOS.sh, vendor/golang.org/x/net/http2/Dockerfile, vendor/golang.org/x/sys/unix/mkall.sh, vendor/google.golang.org/genproto/regen.sh, vendor/k8s.io/apimachinery/hack/godep-deps.sh, vendor/k8s.io/apimachinery/hack/sync-from-kubernetes.sh, vendor/k8s.io/client-go/examples/in-cluster-client-configuration/Dockerfile
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were unable to be fixed. Please review them to see if they can be manually resolved.
* http://apache.mirror.gtcomm.net/kafka/ (200) with 1 occurrences could not be migrated:  
([https](https://apache.mirror.gtcomm.net/kafka/) result AnnotatedConnectException).
* http://cvsweb.netbsd.org/bsdweb.cgi/~checkout~/src/sys/kern/syscalls.master (200) with 3 occurrences could not be migrated:  
([https](https://cvsweb.netbsd.org/bsdweb.cgi/~checkout~/src/sys/kern/syscalls.master) result ConnectTimeoutException).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your …
=> URL Cleanup

pkg/fileutils/paths_test.go, pkg/fileutils/read.go, pkg/fileutils/read_test.go
- on Windows using net/url.Parse with an absolute file path without a scheme but with a drive letter will cause the URL to report the drive letter as the scheme
Fixes #1036
=> Modify the way files paths/URLs/schemes are handled

cmd/riff/main.go, go.mod, go.sum, pkg/core/client.go, pkg/core/function.go, pkg/core/function_test.go, pkg/core/mocks/mockbuilder/Builder.go, pkg/riff/commands/wiring.go
Function authors may define and commit their own riff.toml file which
will be used for both local and on-cluster builds. The riff cli allows
users to override values in the riff.toml when creating a function.
packs now allows environment variables to be passed to the detect and
build phases. The riff cli no longer writes its own riff.toml instead
defering to the user's riff.toml and instead passes it's custom config
as env vars. Function buildpacks understand both riff.toml and the env
var, favoring the environment when there is a conflict.
Refs #1192
=> Allow riff.toml to exist

.travis/fats.sh
...because if we don't update, Build CRD will stop being able to pull the function source for the previous git commit.
=> Use latest FATS

cmd/riff/main.go
The istio.yaml published as part of the Knative Serving release is too
heavy in both the number of replicas and reservations. We previously
scaled it back using a "patch" yaml that duplicates the resources that
needed to change. Now we use a single yaml file with the patch applied.
The diff from the Knative version is also published.
=> Apply the Istio patch to istio.yaml

CODE_OF_CONDUCT.adoc
We're big enough that we should have a contributor code of conduct. It's better to have this in place before something happens.
This is a direct lift from spring. We may want to adjust the reporting email address to be something riff specific down the road, but should be good enough for now.
=> Add contributor covenant

docs/riff_namespace_init.md, pkg/core/namespace.go, pkg/core/namespace_test.go, pkg/riff/commands/namespace.go, pkg/riff/commands/namespace_test.go
- Docker Hub is two words so flag should be `--docker-hub`
- refer to Docker username as Docker ID
- leaving the deprecated `--dockerhub` flag as hidden to accommodate existing scripts, should remove it for next release
=> Fix Docker Hub references for namespace init

azure-pipelines.yml
The name of the installed package switched from docker.io to moby-engine
and moby-cli. So we now uninstall moby-* before installing the older
version of docker.
=> AZP Fix downgrade docker

cmd/riff/main.go
This is the version of Istio that will be included with Knative Serving
0.5.1 and fixes a couple CVEs in Envoy.
Refs #1232
=> Uprade Istio to 1.0.7

pkg/core/function.go
- prevents service account creds from being overwritten
=> Set USE_CRED_HELPERS to false

cmd/riff/main.go, pkg/core/function.go
Update to Knative serving v0.5.1
Fix builds on PKS/GCP with GCR by setting USE_CRED_HELPERS to false. See comments here: https://github.com/buildpack/knative-integration/issues/2#issuecomment-482624665 
Fixes #1249
=> Back-port fixes from master

go.mod, go.sum, pkg/core/kustomize/kustomize.go, pkg/core/kustomize/kustomize_test.go
This upgrades Kustomize to the highest stable version and includes
a simple workaround that can work now because of kustomize
improved normalization logic.
There is an open issue against kustomize to get rid of
normalization entirely when one uses their in-memory FS impl like
riff does: https://github.com/kubernetes-sigs/kustomize/issues/963
Back-port of #1247 commit c65b91bbe3a06421bd2803723a4ed59865fc3d9c
Fixes #1252
=> [BACK-PORT] Fix kustomize integration (#1247)

go.mod, go.sum, pkg/cli/color.go, pkg/cli/config.go, pkg/cli/format.go, pkg/cli/printers/tableprinter.go, pkg/cli/printers/tabwriter.go, pkg/cli/printers/tabwriter/tabwriter.go, pkg/riff/commands/credential_list.go, pkg/riff/commands/handler_list.go
Output is now colorized for table lists with the Format* functions doing
the right thing by default.
This nesessitated hacking the tabwriter since the color code sequences
were affecting the tab width. This was easy to integrate since the
caller is also vendored within our code bases, but will need to be
rethought when we switch to mainline code.
=> Add color to tables

pkg/riff/commands/application_create.go, pkg/riff/commands/application_create_test.go, pkg/riff/commands/function_create.go, pkg/riff/commands/function_create_test.go
Application and Function builds should use the builder defiend within
the cluster. riff system will collect builders into a configmap at
riff-system/builders. We can get the builder image from that config map.
=> Lookup builder from cluster

docs/riff_application_create.md, docs/riff_credential_apply.md, docs/riff_function_create.md, go.mod, go.sum, pkg/cli/flags.go, pkg/riff/commands/application_create.go, pkg/riff/commands/application_create_test.go, pkg/riff/commands/credential_apply.go, pkg/riff/commands/credential_apply_test.go, pkg/riff/commands/function_create.go, pkg/riff/commands/function_create_test.go
The --image flag is now optional for applications and functions. The
default value is `_`, which applies the configured default prefix
with the application/function's name. A custom repo or tag can be
specified like `_/repo:tag`.
For in-cluser builds this resolution occurs in the reconciler. For local
builds, it occurs within the CLI. In both cases, the resolution logic is
defined within projectriff/system.
Depends on https://github.com/projectriff/system/pull/21
=> Backport default image prefix support

pkg/cli/format.go, pkg/riff/commands/application_list.go, pkg/riff/commands/application_list_test.go, pkg/riff/commands/function_list.go, pkg/riff/commands/function_list_test.go, pkg/riff/commands/handler_list.go, pkg/riff/commands/handler_list_test.go, pkg/riff/commands/processor_list.go, pkg/riff/commands/processor_list_test.go, pkg/riff/commands/stream_list.go, pkg/riff/commands/stream_list_test.go
The READY and SUCCEEDED columns are now a uniform STATUS column, the
value within the column is no longer "True", but "Ready" or "Succeeded"
depending on the condition type.
If the condition is false, the reason is printed as an error.
=> Normalize READY/SUCCEEDED columns in listings

Makefile
Fixes error below when using `make clean` before `./riff` exists.
```
$ make clean
rm riff
rm: riff: No such file or directory
make: *** [clean] Error 1
```
=> clean without error when ./riff is not present

azure-pipelines.yml, ci/install-gcloud.yml, ci/publish.sh
changes from v0.3.0:
- publish depends directly on unit since there are no fats test (yet)
- TRAVIS_BRANCH has been removed in favor of an argument
=> Backport CI artifact publishing

docs/riff_application_create.md, docs/riff_function_create.md, docs/riff_handler_create.md, docs/riff_processor_create.md, pkg/cli/flags.go, pkg/k8s/wait.go, pkg/riff/commands/application_create.go, pkg/riff/commands/application_create_test.go, pkg/riff/commands/function_create.go, pkg/riff/commands/function_create_test.go, pkg/riff/commands/handler_create.go, pkg/riff/commands/handler_create_test.go, pkg/riff/commands/processor_create.go, pkg/riff/commands/processor_create_test.go
By default, wait 10 minutes for a created resource to become ready. This
value can be overridden with the --wait-timeout flag. When a timeout
occurs the user is given commands to check the resource status and
continue watching logs.
=> Wait 10 mins for a new resource to become ready

go.sum, pkg/riff/commands/application_create_test.go, pkg/riff/commands/function_create_test.go, pkg/riff/commands/handler_create_test.go, pkg/riff/commands/handler_invoke_test.go, pkg/riff/commands/processor_create_test.go, pkg/testing/command_table.go
- silence errors in command output
- avoid clobbering errors in table
- assert errors in Verify func rather than command output
=> Cleanup command test error handling

ci/fats.sh, pkg/riff/commands/application_create_test.go, pkg/riff/commands/function_create_test.go, pkg/riff/commands/handler_create_test.go, pkg/riff/commands/processor_create_test.go
- only run command function, other languages are tested as part of
creating the builder image and creating the bundle
- assert chucks of output for racy commands. Logs are emitted from
different goroutines. For real commands enough wall time will have
elapsed to make race meaningless
=> Reduce test flakes

cmd/riff/main.go, pkg/cli/errors.go, pkg/cli/sort.go, pkg/k8s/wait.go, pkg/riff/commands/application_create.go, pkg/riff/commands/application_create_test.go, pkg/riff/commands/function_create.go, pkg/riff/commands/function_create_test.go, pkg/riff/commands/handler_create.go, pkg/riff/commands/handler_create_test.go, pkg/riff/commands/processor_create.go, pkg/riff/commands/processor_create_test.go
- no more race conditions
- consistent log output
- push timeout into the context
=> Properly control flow waiting for a resource to become ready

pkg/riff/commands/application_create.go, pkg/riff/commands/function_create.go, pkg/riff/commands/handler_create.go, pkg/riff/commands/processor_create.go
Since we can’t rule out the case where either WaitUntilReady() or
ApplicationLogs() (or both) return an error just before the context expires,
the current code can deadlock. See this example flow in the case of both
failing: https://play.golang.org/p/76Dcr9VlAXo. A solution is to increase the
buffer size to 3 so that the main thread will never block on sending an error
to the channel.
=> Avoid deadlocks during create

pkg/riff/commands/application_create.go, pkg/riff/commands/function_create.go, pkg/riff/commands/handler_create.go, pkg/riff/commands/processor_create.go, pkg/util/timeout.go, pkg/util/timeout_test.go
Create a race util that will return with the first task to complete.
Each task is run in an independent go routine. If no task completes the
whole process will timeout.
=> Normalize tail control flow

azure-pipelines.yml, ci/fats.sh
For pull requests, FATS provides more friction than benefit. The
important thing is for the cli to be fully tested before release
artifacts are published. We still run FATS for pushed commits, it is
only skipped for pull requests.
...also adding a TODO to add Windows FATS tests.
=> Drop FATS lite

docs/riff.md, docs/riff_doctor.md, pkg/riff/commands/doctor.go, pkg/riff/commands/doctor_test.go, pkg/riff/commands/riff.go, pkg/riff/commands/riff_test.go
from hack.commit.push Paris
Added command `riff doctor` to check if the follow namespaces are installed for riff:
- istio-system
- knative-build
- knative-serving
- riff-system
like this
```
➜  riff git:(feature/riff-doctor) ./riff doctor
Installation is OK
```
or
```
➜  riff git:(feature/riff-doctor) ./riff doctor
Something is wrong!
missing istio-system
missing knative-build
missing knative-serving
missing riff-system
```
co-worked from https://github.com/davidthou & https://github.com/zhitongliu
=> Add riff doctor
